# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  About: about  # 关于
  #Links: /links

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: Hexo # 页面title
  favicon: /favicon.png
  board: <p>欢迎交流与分享经验!</p> # 站点公告
  copyright: false # 底部版权信息

# config
config:
  skin: # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More
  #New
  isNewTabLinks: false #是否链接打开新标签页
  autoUnfold: true # 默认展开文章目录

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true
  midSize: 2 # 当前页码左右到省略号显示的页码数，默认2，表现为 1 ... 4 5 6 7 8 ... 10
  showContent: true # 页面文章小于2篇时显示文章内容

# Sidebar
sidebar: right
widgets:
  - category
  - tag
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: false
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.png
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/alipayimg.png 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: false  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
# github: 
#   username: cofess  # github username

# Repository Info (This will override 'github' option)
# 项目仓库信息（将会覆盖 github 项）
repository:
  platform: github # 托管平台（github | gitee）
  username: wangwanqiang # 用户名

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: gitalk  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner: wangwanqiang  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin: wangwanqiang  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo: wangwanqiang.github.io  #必须. GitHub repository.
    ClientID: 8cf70ec83c0f2297a66a  #必须. GitHub Application Client ID.
    ClientSecret: 39bce8b25292774ac59158f33fcaf06057d1dcec  #必须. GitHub Application Client Secret.
    enableHotKey: true
    language: zh-CN
    
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier
    verify: false # verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    language: zh-cn # language, available values: en, zh-cn
    visitor: false # article reading statistic
    recordIP: false # whether to record the commenter IP

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  apikey: # 豆瓣apikey
  
# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  leancloud:
    enable: false  # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: false
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: 0GUyfSKVO6ZMFM5NT-oLy1BeO_LQPEcnGhTn3xTvklI # enter Google site verification code
  baidu_analytics: 0659e54213d527762148d926eefbbdc7 # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  articleSelfBlock: false # 关闭文章下方的自我介绍
  avatar: images/avatar.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Wanqiang
  author_title: WDeveloper
  author_description: 无话可说。
  location: 中国
  follow: https://github.com/wangwanqiang
  # Social Links
  social:
    links:
      github: https://github.com/wangwanqiang
      #weibo: http://weibo.com/
      #twitter: https://twitter.com/
      #facebook: /
      #dribbble: /
      #behance: /
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    Git: ★★★★☆
    JavaScript: ★★★☆☆
    HTML+CSS: ★★★★☆
    Node.js: ★★★☆☆
  # My Personal Links
  links:
    Github: https://github.com/wangwanqiang
    #Blog: /
    #微博: http://weibo.com/
  # My Personal Labels
  labels:
    - 前端
    - 开发
    - JavaScript
    - 博客
  # My Personal Works
  #works:
  #  name:
  #    link: http://www.example.com
  #    date: 2023
  # My Personal Projects
  projects:
    wangwanqiang/hexoComment: https://github.com/wangwanqiang/hexoComment
    wangwanqiang/hexo-theme-pure: https://github.com/wangwanqiang/hexo-theme-pure