name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
        
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    
    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install hexo-cli
      #if: steps.cache.outputs.cache-hit != 'true'
      run: npm install -g hexo-cli
      
    - name: Install npm nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '20.19.0'
     #-run: npm install
      
     #run: npm install
      
    - name: show hexo version
      run: |
        npm update
        hexo version
        npm outdated
        npm fund
        
    - name: run generate
      run: |
        hexo clean
        hexo generate
        
    
    # Deploy hexo blog website.
    - name: Deploy
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        cd ./public
        git init
        git add -A
        git commit -m "Update docs by GitHub Actions"
        git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/wangwanqiang/wangwanqiang.github.com.git master
