name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
        
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    
    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install hexo-cli
      #if: steps.cache.outputs.cache-hit != 'true'
      run: npm install -g hexo-cli
      
    - name: Install npm nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
     #-run: npm install
      
     #run: npm install
      
    - name: run test
      run: |
        echo "$MY_NAME"
    - name: run generate
      run: |
        hexo clean
        hexo generate
        
    
    # Deploy hexo blog website.
    - name: Deploy
      run: |
        ls -al
        cd ./public
        ls -al
        git init
        git config user.name "github-ci"
        git config user.email "wwq100@gmail.com"
        git add .
        git commit -m "Update docs by GitHub"
        git push --force --quiet "https://${{ secrets.DEPLOY_KEY }}@github.com/wangwanqiang/wangwanqiang.github.com" master:master
      
    # Use the output from the `deploy` step(use for test action)
    - name: Get the output
      run: |
        hexo version
